// 명명 유니버스 — 포트폴리오 config.universeRef / syncUniverseRef 로 이름만 참조.
// 대형 종목 목록(수백 개)을 포트폴리오 DB 문서에서 분리해 여기로 뺐다.
// 인덱스 리밸런싱 시 이 파일만 갱신하면 되고, 포트폴리오는 이름만 들고 있다.

export const UNIVERSES: Record<string, string[]> = {
  // KOSPI200 + 국장 레버리지/인버스 ETF (069500 v4 가격 push, 211종목)
  "kospi200-kr": [
    "000080", "000100", "000120", "000150", "000210", "000240", "000270", "000660",
    "000670", "000720", "000810", "000880", "000990", "001040", "001430", "001440",
    "001450", "001680", "001800", "002030", "002380", "002790", "002840", "003030",
    "003090", "003230", "003240", "003490", "003550", "003670", "004000", "004020",
    "004170", "004370", "004990", "005300", "005380", "005420", "005490", "005830",
    "005850", "005930", "005940", "006040", "006260", "006280", "006400", "006650",
    "006800", "007070", "007310", "007340", "007660", "008730", "008770", "008930",
    "009150", "009240", "009420", "009540", "009830", "009970", "010060", "010120",
    "010130", "010140", "010950", "011070", "011170", "011200", "011210", "011780",
    "011790", "012330", "012450", "0126Z0", "012750", "014680", "014820", "015760",
    "016360", "017670", "017800", "017960", "018260", "018880", "021240", "022100",
    "023530", "024110", "026960", "028050", "028260", "028670", "029780", "030000",
    "030200", "032640", "032830", "033780", "034020", "034220", "034230", "034730",
    "035250", "035420", "035720", "036460", "036570", "039490", "042660", "042700",
    "047040", "047050", "047810", "051600", "051900", "051910", "052690", "055550",
    "062040", "064350", "064400", "066570", "066970", "068270", "069260", "069620",
    "069960", "071050", "071320", "071970", "073240", "078930", "079550", "081660",
    "082740", "086280", "086790", "088350", "090430", "093370", "096770", "097950",
    "103140", "105560", "111770", "112610", "120110", "128940", "137310", "138040",
    "138930", "139130", "139480", "161390", "161890", "175330", "180640", "185750",
    "192080", "192820", "204320", "207940", "241560", "251270", "259960", "267250",
    "267260", "267270", "268280", "271560", "272210", "278470", "280360", "282330",
    "285130", "298020", "298040", "298050", "300720", "302440", "307950", "316140",
    "323410", "326030", "329180", "352820", "361610", "373220", "375500", "377300",
    "383220", "402340", "443060", "450080", "454910", "456040", "457190", "483650",
    "069500", "122630", "252670", "233740", "251340", "409820", "423920", "418660",
    "494310", "243880", "462330",
  ],
  // 미장 trend 매매 유니버스 (514종목)
  "sp500-us": [
    "MMM", "AOS", "ABT", "ABBV", "ACN", "ADBE", "AMD", "AES",
    "AFL", "A", "APD", "ABNB", "AKAM", "ALB", "ARE", "ALGN",
    "ALLE", "LNT", "ALL", "GOOGL", "GOOG", "MO", "AMZN", "AMCR",
    "AEE", "AEP", "AXP", "AIG", "AMT", "AWK", "AMP", "AME",
    "AMGN", "APH", "ADI", "AON", "APA", "APO", "AAPL", "AMAT",
    "APP", "APTV", "ACGL", "ADM", "ARES", "ANET", "AJG", "AIZ",
    "T", "ATO", "ADSK", "ADP", "AZO", "AVB", "AVY", "AXON",
    "BKR", "BALL", "BAC", "BAX", "BDX", "BRKB", "BBY", "TECH",
    "BIIB", "BLK", "BX", "XYZ", "BNY", "BA", "BKNG", "BSX",
    "BMY", "AVGO", "BR", "BRO", "BFB", "BLDR", "BG", "BXP",
    "CHRW", "CDNS", "CPT", "COF", "CAH", "CCL", "CARR", "CVNA",
    "CASY", "CAT", "CBOE", "CBRE", "CDW", "COR", "CNC", "CNP",
    "CF", "CRL", "SCHW", "CHTR", "CVX", "CMG", "CB", "CHD",
    "CIEN", "CI", "CINF", "CTAS", "CSCO", "C", "CFG", "CLX",
    "CME", "CMS", "KO", "CTSH", "COHR", "COIN", "CL", "CMCSA",
    "FIX", "COP", "ED", "STZ", "CEG", "COO", "CPRT", "GLW",
    "CPAY", "CTVA", "CSGP", "COST", "CRH", "CRWD", "CCI", "CSX",
    "CMI", "CVS", "DHR", "DRI", "DDOG", "DVA", "DECK", "DE",
    "DELL", "DAL", "DVN", "DXCM", "FANG", "DLR", "DG", "DLTR",
    "D", "DPZ", "DASH", "DOV", "DOW", "DHI", "DTE", "DUK",
    "DD", "ETN", "EBAY", "ECHO", "ECL", "EIX", "EW", "EA",
    "ELV", "EME", "EMR", "ETR", "EOG", "EQT", "EFX", "EQIX",
    "EQR", "ERIE", "ESS", "EL", "EG", "EVRG", "ES", "EXC",
    "EXE", "EXPE", "EXPD", "EXR", "XOM", "FFIV", "FDS", "FICO",
    "FAST", "FRT", "FDX", "FDXF", "FIS", "FITB", "FSLR", "FE",
    "FISV", "FLEX", "F", "FTNT", "FTV", "FOXA", "FOX", "BEN",
    "FCX", "GRMN", "IT", "GE", "GEHC", "GEV", "GEN", "GNRC",
    "GD", "GIS", "GM", "GPC", "GILD", "GPN", "GL", "GDDY",
    "GS", "HAL", "HIG", "HAS", "HCA", "DOC", "HSIC", "HSY",
    "HPE", "HLT", "HD", "HONA", "HON", "HRL", "HST", "HWM",
    "HPQ", "HUBB", "HUM", "HBAN", "HII", "IBM", "IEX", "IDXX",
    "ITW", "INCY", "IR", "PODD", "INTC", "IBKR", "ICE", "IFF",
    "IP", "INTU", "ISRG", "IVZ", "INVH", "IQV", "IRM", "JBHT",
    "JBL", "JKHY", "J", "JNJ", "JCI", "JPM", "KVUE", "KDP",
    "KEY", "KEYS", "KMB", "KIM", "KMI", "KKR", "KLAC", "KHC",
    "KR", "LHX", "LH", "LRCX", "LVS", "LDOS", "LEN", "LII",
    "LLY", "LIN", "LYV", "LMT", "L", "LOW", "LULU", "LITE",
    "LYB", "MTB", "MPC", "MAR", "MRSH", "MLM", "MRVL", "MAS",
    "MA", "MKC", "MCD", "MCK", "MDT", "MRK", "META", "MET",
    "MTD", "MGM", "MCHP", "MU", "MSFT", "MAA", "MRNA", "TAP",
    "MDLZ", "MPWR", "MNST", "MCO", "MS", "MOS", "MSI", "MSCI",
    "NDAQ", "NTAP", "NFLX", "NEM", "NWSA", "NWS", "NEE", "NKE",
    "NI", "NDSN", "NSC", "NTRS", "NOC", "NCLH", "NRG", "NUE",
    "NVDA", "NVR", "NXPI", "ORLY", "OXY", "ODFL", "OMC", "ON",
    "OKE", "ORCL", "OTIS", "PCAR", "PKG", "PLTR", "PANW", "PSKY",
    "PH", "PAYX", "PYPL", "PNR", "PEP", "PFE", "PCG", "PM",
    "PSX", "PNW", "PNC", "PPG", "PPL", "PFG", "PG", "PGR",
    "PLD", "PRU", "PEG", "PTC", "PSA", "PHM", "PWR", "QCOM",
    "DGX", "Q", "RL", "RJF", "RTX", "O", "REG", "REGN",
    "RF", "RSG", "RMD", "RVTY", "HOOD", "ROK", "ROL", "ROP",
    "ROST", "RCL", "SPGI", "CRM", "SNDK", "SBAC", "SLB", "STX",
    "SRE", "NOW", "SHW", "SPG", "SWKS", "SJM", "SW", "SNA",
    "SOLV", "SO", "LUV", "SWK", "SBUX", "STT", "STLD", "STE",
    "SYK", "SMCI", "SYF", "SNPS", "SYY", "TMUS", "TROW", "TTWO",
    "TPR", "TRGP", "TGT", "TEL", "TDY", "TER", "TSLA", "TXN",
    "TPL", "TXT", "TMO", "TJX", "TKO", "TTD", "TSCO", "TT",
    "TDG", "TRV", "TRMB", "TFC", "TYL", "TSN", "USB", "UBER",
    "UDR", "ULTA", "UNP", "UAL", "UPS", "URI", "UNH", "UHS",
    "VLO", "VEEV", "VTR", "VLTO", "VRSN", "VRSK", "VZ", "VRTX",
    "VRT", "VTRS", "VICI", "V", "VST", "VMC", "WRB", "GWW",
    "WAB", "WMT", "DIS", "WBD", "WM", "WAT", "WEC", "WFC",
    "WELL", "WST", "WDC", "WY", "WSM", "WMB", "WTW", "WDAY",
    "WYNN", "XEL", "XYL", "YUM", "ZBRA", "ZBH", "ZTS", "QQQ",
    "TQQQ", "SQQQ", "SPY", "VOO", "UPRO", "SOXL", "TECL", "TNA",
    "FAS", "LABU",
  ],
};

// 종목 → 거래소 코드(NYS/NAS/AMS) — 미장 시세/주문 라우팅. universe 와 짝.
export const EXCD_MAPS: Record<string, Record<string, string>> = {
  "sp500-us": {
    MMM: "NYS", AOS: "NYS", ABT: "NYS", ABBV: "NYS", ACN: "NYS", ADBE: "NAS",
    AMD: "NAS", AES: "NYS", AFL: "NYS", A: "NYS", APD: "NYS", ABNB: "NAS",
    AKAM: "NAS", ALB: "NYS", ARE: "NYS", ALGN: "NAS", ALLE: "NYS", LNT: "NAS",
    ALL: "NYS", GOOGL: "NAS", GOOG: "NAS", MO: "NYS", AMZN: "NAS", AMCR: "NYS",
    AEE: "NYS", AEP: "NAS", AXP: "NYS", AIG: "NYS", AMT: "NYS", AWK: "NYS",
    AMP: "NYS", AME: "NYS", AMGN: "NAS", APH: "NYS", ADI: "NAS", AON: "NYS",
    APA: "NAS", APO: "NYS", AAPL: "NAS", AMAT: "NAS", APP: "NAS", APTV: "NYS",
    ACGL: "NAS", ADM: "NYS", ARES: "NYS", ANET: "NYS", AJG: "NYS", AIZ: "NYS",
    T: "NYS", ATO: "NYS", ADSK: "NAS", ADP: "NAS", AZO: "NYS", AVB: "NYS",
    AVY: "NYS", AXON: "NAS", BKR: "NAS", BALL: "NYS", BAC: "NYS", BAX: "NYS",
    BDX: "NYS", BRKB: "NYS", BBY: "NYS", TECH: "NAS", BIIB: "NAS", BLK: "NYS",
    BX: "NYS", XYZ: "NYS", BNY: "NYS", BA: "NYS", BKNG: "NAS", BSX: "NYS",
    BMY: "NYS", AVGO: "NAS", BR: "NYS", BRO: "NYS", BFB: "NYS", BLDR: "NYS",
    BG: "NYS", BXP: "NYS", CHRW: "NAS", CDNS: "NAS", CPT: "NYS", COF: "NYS",
    CAH: "NYS", CCL: "NYS", CARR: "NYS", CVNA: "NYS", CASY: "NAS", CAT: "NYS",
    CBOE: "NYS", CBRE: "NYS", CDW: "NAS", COR: "NYS", CNC: "NYS", CNP: "NYS",
    CF: "NYS", CRL: "NYS", SCHW: "NYS", CHTR: "NAS", CVX: "NYS", CMG: "NYS",
    CB: "NYS", CHD: "NYS", CIEN: "NYS", CI: "NYS", CINF: "NAS", CTAS: "NAS",
    CSCO: "NAS", C: "NYS", CFG: "NYS", CLX: "NYS", CME: "NAS", CMS: "NYS",
    KO: "NYS", CTSH: "NAS", COHR: "NYS", COIN: "NAS", CL: "NYS", CMCSA: "NAS",
    FIX: "NYS", COP: "NYS", ED: "NYS", STZ: "NYS", CEG: "NAS", COO: "NAS",
    CPRT: "NAS", GLW: "NYS", CPAY: "NYS", CTVA: "NYS", CSGP: "NAS", COST: "NAS",
    CRH: "NYS", CRWD: "NAS", CCI: "NYS", CSX: "NAS", CMI: "NYS", CVS: "NYS",
    DHR: "NYS", DRI: "NYS", DDOG: "NAS", DVA: "NYS", DECK: "NYS", DE: "NYS",
    DELL: "NYS", DAL: "NYS", DVN: "NYS", DXCM: "NAS", FANG: "NAS", DLR: "NYS",
    DG: "NYS", DLTR: "NAS", D: "NYS", DPZ: "NAS", DASH: "NAS", DOV: "NYS",
    DOW: "NYS", DHI: "NYS", DTE: "NYS", DUK: "NYS", DD: "NYS", ETN: "NYS",
    EBAY: "NAS", ECHO: "NAS", ECL: "NYS", EIX: "NYS", EW: "NYS", EA: "NAS",
    ELV: "NYS", EME: "NYS", EMR: "NYS", ETR: "NYS", EOG: "NYS", EQT: "NYS",
    EFX: "NYS", EQIX: "NAS", EQR: "NYS", ERIE: "NAS", ESS: "NYS", EL: "NYS",
    EG: "NYS", EVRG: "NAS", ES: "NYS", EXC: "NAS", EXE: "NAS", EXPE: "NAS",
    EXPD: "NYS", EXR: "NYS", XOM: "NYS", FFIV: "NAS", FDS: "NYS", FICO: "NYS",
    FAST: "NAS", FRT: "NYS", FDX: "NYS", FDXF: "NYS", FIS: "NYS", FITB: "NYS",
    FSLR: "NAS", FE: "NYS", FISV: "NAS", FLEX: "NAS", F: "NYS", FTNT: "NAS",
    FTV: "NYS", FOXA: "NAS", FOX: "NAS", BEN: "NYS", FCX: "NYS", GRMN: "NYS",
    IT: "NYS", GE: "NYS", GEHC: "NAS", GEV: "NYS", GEN: "NAS", GNRC: "NYS",
    GD: "NYS", GIS: "NYS", GM: "NYS", GPC: "NYS", GILD: "NAS", GPN: "NYS",
    GL: "NYS", GDDY: "NYS", GS: "NYS", HAL: "NYS", HIG: "NYS", HAS: "NAS",
    HCA: "NYS", DOC: "NYS", HSIC: "NAS", HSY: "NYS", HPE: "NYS", HLT: "NYS",
    HD: "NYS", HONA: "NAS", HON: "NAS", HRL: "NYS", HST: "NAS", HWM: "NYS",
    HPQ: "NYS", HUBB: "NYS", HUM: "NYS", HBAN: "NAS", HII: "NYS", IBM: "NYS",
    IEX: "NYS", IDXX: "NAS", ITW: "NYS", INCY: "NAS", IR: "NYS", PODD: "NAS",
    INTC: "NAS", IBKR: "NAS", ICE: "NYS", IFF: "NYS", IP: "NYS", INTU: "NAS",
    ISRG: "NAS", IVZ: "NYS", INVH: "NYS", IQV: "NYS", IRM: "NYS", JBHT: "NAS",
    JBL: "NYS", JKHY: "NAS", J: "NYS", JNJ: "NYS", JCI: "NYS", JPM: "NYS",
    KVUE: "NYS", KDP: "NAS", KEY: "NYS", KEYS: "NYS", KMB: "NAS", KIM: "NYS",
    KMI: "NYS", KKR: "NYS", KLAC: "NAS", KHC: "NAS", KR: "NYS", LHX: "NYS",
    LH: "NYS", LRCX: "NAS", LVS: "NYS", LDOS: "NYS", LEN: "NYS", LII: "NYS",
    LLY: "NYS", LIN: "NAS", LYV: "NYS", LMT: "NYS", L: "NYS", LOW: "NYS",
    LULU: "NAS", LITE: "NAS", LYB: "NYS", MTB: "NYS", MPC: "NYS", MAR: "NAS",
    MRSH: "NYS", MLM: "NYS", MRVL: "NAS", MAS: "NYS", MA: "NYS", MKC: "NYS",
    MCD: "NYS", MCK: "NYS", MDT: "NYS", MRK: "NYS", META: "NAS", MET: "NYS",
    MTD: "NYS", MGM: "NYS", MCHP: "NAS", MU: "NAS", MSFT: "NAS", MAA: "NYS",
    MRNA: "NAS", TAP: "NYS", MDLZ: "NAS", MPWR: "NAS", MNST: "NAS", MCO: "NYS",
    MS: "NYS", MOS: "NYS", MSI: "NYS", MSCI: "NYS", NDAQ: "NAS", NTAP: "NAS",
    NFLX: "NAS", NEM: "NYS", NWSA: "NAS", NWS: "NAS", NEE: "NYS", NKE: "NYS",
    NI: "NYS", NDSN: "NAS", NSC: "NYS", NTRS: "NAS", NOC: "NYS", NCLH: "NYS",
    NRG: "NYS", NUE: "NYS", NVDA: "NAS", NVR: "NYS", NXPI: "NAS", ORLY: "NAS",
    OXY: "NYS", ODFL: "NAS", OMC: "NYS", ON: "NAS", OKE: "NYS", ORCL: "NYS",
    OTIS: "NYS", PCAR: "NAS", PKG: "NYS", PLTR: "NAS", PANW: "NAS", PSKY: "NAS",
    PH: "NYS", PAYX: "NAS", PYPL: "NAS", PNR: "NYS", PEP: "NAS", PFE: "NYS",
    PCG: "NYS", PM: "NYS", PSX: "NYS", PNW: "NYS", PNC: "NYS", PPG: "NYS",
    PPL: "NYS", PFG: "NAS", PG: "NYS", PGR: "NYS", PLD: "NYS", PRU: "NYS",
    PEG: "NYS", PTC: "NAS", PSA: "NYS", PHM: "NYS", PWR: "NYS", QCOM: "NAS",
    DGX: "NYS", Q: "NYS", RL: "NYS", RJF: "NYS", RTX: "NYS", O: "NYS",
    REG: "NAS", REGN: "NAS", RF: "NYS", RSG: "NYS", RMD: "NYS", RVTY: "NYS",
    HOOD: "NAS", ROK: "NYS", ROL: "NYS", ROP: "NAS", ROST: "NAS", RCL: "NYS",
    SPGI: "NYS", CRM: "NYS", SNDK: "NAS", SBAC: "NAS", SLB: "NYS", STX: "NAS",
    SRE: "NYS", NOW: "NYS", SHW: "NYS", SPG: "NYS", SWKS: "NAS", SJM: "NYS",
    SW: "NYS", SNA: "NYS", SOLV: "NYS", SO: "NYS", LUV: "NYS", SWK: "NYS",
    SBUX: "NAS", STT: "NYS", STLD: "NAS", STE: "NYS", SYK: "NYS", SMCI: "NAS",
    SYF: "NYS", SNPS: "NAS", SYY: "NYS", TMUS: "NAS", TROW: "NAS", TTWO: "NAS",
    TPR: "NYS", TRGP: "NYS", TGT: "NYS", TEL: "NYS", TDY: "NYS", TER: "NAS",
    TSLA: "NAS", TXN: "NAS", TPL: "NYS", TXT: "NYS", TMO: "NYS", TJX: "NYS",
    TKO: "NYS", TTD: "NAS", TSCO: "NAS", TT: "NYS", TDG: "NYS", TRV: "NYS",
    TRMB: "NAS", TFC: "NYS", TYL: "NYS", TSN: "NYS", USB: "NYS", UBER: "NYS",
    UDR: "NYS", ULTA: "NAS", UNP: "NYS", UAL: "NAS", UPS: "NYS", URI: "NYS",
    UNH: "NYS", UHS: "NYS", VLO: "NYS", VEEV: "NYS", VTR: "NYS", VLTO: "NYS",
    VRSN: "NAS", VRSK: "NAS", VZ: "NYS", VRTX: "NAS", VRT: "NYS", VTRS: "NAS",
    VICI: "NYS", V: "NYS", VST: "NYS", VMC: "NYS", WRB: "NYS", GWW: "NYS",
    WAB: "NYS", WMT: "NAS", DIS: "NYS", WBD: "NAS", WM: "NYS", WAT: "NYS",
    WEC: "NYS", WFC: "NYS", WELL: "NYS", WST: "NYS", WDC: "NAS", WY: "NYS",
    WSM: "NYS", WMB: "NYS", WTW: "NAS", WDAY: "NAS", WYNN: "NAS", XEL: "NAS",
    XYL: "NYS", YUM: "NYS", ZBRA: "NAS", ZBH: "NYS", ZTS: "NYS", QQQ: "NAS",
    TQQQ: "NAS", SQQQ: "NAS", SPY: "AMS", VOO: "AMS", UPRO: "AMS", SOXL: "AMS",
    TECL: "AMS", TNA: "AMS", FAS: "AMS", LABU: "AMS",
  },
};
